"""client

Revision ID: 25840d9bba21
Revises: 82dd70e58574
Create Date: 2026-03-29 18:37:50.318551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25840d9bba21'
down_revision: Union[str, Sequence[str], None] = '82dd70e58574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_code', sa.String(length=64), nullable=True),
    sa.Column('client_number', sa.String(length=64), nullable=True),
    sa.Column('client_business_number', sa.String(length=128), nullable=True),
    sa.Column('client_company_name', sa.String(length=256), nullable=True),
    sa.Column('client_contact_name', sa.String(length=128), nullable=True),
    sa.Column('client_contact_title', sa.String(length=128), nullable=True),
    sa.Column('client_address', sa.String(length=512), nullable=True),
    sa.Column('client_email', sa.String(length=128), nullable=True),
    sa.Column('client_mainphone', sa.String(length=64), nullable=True),
    sa.Column('client_secondphone', sa.String(length=64), nullable=True),
    sa.Column('client_fax', sa.String(length=64), nullable=True),
    sa.Column('client_website', sa.String(length=256), nullable=True),
    sa.Column('client_currency', sa.String(length=16), nullable=True),
    sa.Column('client_tax_id', sa.String(length=128), nullable=True),
    sa.Column('client_payment_term', sa.Integer(), nullable=True),
    sa.Column('client_payment_method', sa.String(length=64), nullable=True),
    sa.Column('client_template_id', sa.String(length=32), nullable=True),
    sa.Column('client_terms_conditions', sa.String(length=1024), nullable=True),
    sa.Column('client_note', sa.String(length=1024), nullable=True),
    sa.Column('client_status', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('zme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_biz_id'), 'clients', ['biz_id'], unique=False)
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=False)
    op.create_index(op.f('ix_clients_created_by'), 'clients', ['created_by'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_owner_id'), 'clients', ['owner_id'], unique=False)
    op.create_index(op.f('ix_clients_ten_id'), 'clients', ['ten_id'], unique=False)
    op.create_index(op.f('ix_clients_zme_id'), 'clients', ['zme_id'], unique=False)
    op.create_table('items',
    sa.Column('item_code', sa.String(length=64), nullable=True),
    sa.Column('item_number', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=256), nullable=True),
    sa.Column('item_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('item_unit_of_measure', sa.String(length=64), nullable=True),
    sa.Column('item_unit', sa.String(length=64), nullable=True),
    sa.Column('item_sku', sa.String(length=128), nullable=True),
    sa.Column('item_description', sa.String(length=1024), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('item_note', sa.String(length=1024), nullable=True),
    sa.Column('item_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('zme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_biz_id'), 'items', ['biz_id'], unique=False)
    op.create_index(op.f('ix_items_created_by'), 'items', ['created_by'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_item_code'), 'items', ['item_code'], unique=False)
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_items_ten_id'), 'items', ['ten_id'], unique=False)
    op.create_index(op.f('ix_items_zme_id'), 'items', ['zme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_zme_id'), table_name='items')
    op.drop_index(op.f('ix_items_ten_id'), table_name='items')
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_index(op.f('ix_items_item_code'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_created_by'), table_name='items')
    op.drop_index(op.f('ix_items_biz_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_clients_zme_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_ten_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_owner_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_by'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_index(op.f('ix_clients_biz_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
