"""zme_id

Revision ID: 288e77ef469f
Revises: 41818f461912
Create Date: 2026-03-29 17:00:46.826541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288e77ef469f'
down_revision: Union[str, Sequence[str], None] = '41818f461912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('zme_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_plans_zme_id'), 'plans', ['zme_id'], unique=False)
    op.alter_column('zbe', 'zme_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('zbe_zme_id_fkey'), 'zbe', type_='foreignkey')
    op.add_column('zme', sa.Column('zme_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_zme_zme_id'), 'zme', ['zme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zme_zme_id'), table_name='zme')
    op.drop_column('zme', 'zme_id')
    op.create_foreign_key(op.f('zbe_zme_id_fkey'), 'zbe', 'zme', ['zme_id'], ['id'])
    op.alter_column('zbe', 'zme_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_plans_zme_id'), table_name='plans')
    op.drop_column('plans', 'zme_id')
    # ### end Alembic commands ###
