"""zbe

Revision ID: 41818f461912
Revises: dd184ae25d9c
Create Date: 2026-03-29 16:49:01.176590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41818f461912'
down_revision: Union[str, Sequence[str], None] = 'dd184ae25d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zbe', sa.Column('be_plan1_expired', sa.DateTime(timezone=True), nullable=True))
    op.add_column('zbe', sa.Column('be_plan10_expired', sa.DateTime(timezone=True), nullable=True))
    op.add_column('zbe', sa.Column('be_plan100_expired', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('zbe', 'be_plan252_expired')
    op.drop_column('zbe', 'be_plan258_expired')
    op.drop_column('zbe', 'be_plan251_expired')
    op.drop_column('zbe', 'be_plan255_expired')
    op.drop_column('zbe', 'be_plan253_expired')
    op.drop_column('zbe', 'be_plan259_expired')
    op.drop_column('zbe', 'be_plan257_expired')
    op.drop_column('zbe', 'be_plan256_expired')
    op.drop_column('zbe', 'be_plan254_expired')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zbe', sa.Column('be_plan254_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('zbe', sa.Column('be_plan256_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('zbe', sa.Column('be_plan257_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('zbe', sa.Column('be_plan259_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('zbe', sa.Column('be_plan253_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('zbe', sa.Column('be_plan255_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('zbe', sa.Column('be_plan251_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('zbe', sa.Column('be_plan258_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('zbe', sa.Column('be_plan252_expired', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('zbe', 'be_plan100_expired')
    op.drop_column('zbe', 'be_plan10_expired')
    op.drop_column('zbe', 'be_plan1_expired')
    # ### end Alembic commands ###
