"""zbe

Revision ID: 7380f6b8606d
Revises: a717e138b33d
Create Date: 2026-03-29 16:04:37.407491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7380f6b8606d'
down_revision: Union[str, Sequence[str], None] = 'a717e138b33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('plan_code', sa.String(length=64), nullable=True),
    sa.Column('plan_name', sa.String(length=128), nullable=True),
    sa.Column('plan_price', sa.String(length=64), nullable=True),
    sa.Column('plan_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_biz_id'), 'plans', ['biz_id'], unique=False)
    op.create_index(op.f('ix_plans_created_by'), 'plans', ['created_by'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_owner_id'), 'plans', ['owner_id'], unique=False)
    op.create_index(op.f('ix_plans_ten_id'), 'plans', ['ten_id'], unique=False)
    op.create_table('zbe',
    sa.Column('zme_id', sa.Uuid(), nullable=False),
    sa.Column('be_logo', sa.String(length=512), nullable=True),
    sa.Column('be_name', sa.String(length=256), nullable=True),
    sa.Column('be_contact', sa.String(length=128), nullable=True),
    sa.Column('be_contact_title', sa.String(length=128), nullable=True),
    sa.Column('be_address', sa.String(length=512), nullable=True),
    sa.Column('be_email', sa.String(length=128), nullable=True),
    sa.Column('be_phone', sa.String(length=64), nullable=True),
    sa.Column('be_website', sa.String(length=256), nullable=True),
    sa.Column('be_type', sa.String(length=64), nullable=True),
    sa.Column('be_biz_number', sa.String(length=128), nullable=True),
    sa.Column('be_tax_id', sa.String(length=128), nullable=True),
    sa.Column('be_bank_info', sa.String(length=1024), nullable=True),
    sa.Column('be_payment_term', sa.Integer(), nullable=True),
    sa.Column('be_currency', sa.String(length=16), nullable=True),
    sa.Column('be_inv_template_id', sa.String(length=32), nullable=True),
    sa.Column('be_description', sa.String(length=1024), nullable=True),
    sa.Column('be_note', sa.String(length=1024), nullable=True),
    sa.Column('be_timezone', sa.String(length=64), nullable=True),
    sa.Column('be_date_format', sa.String(length=32), nullable=True),
    sa.Column('be_inv_prefix', sa.String(length=32), nullable=True),
    sa.Column('be_inv_integer', sa.Integer(), nullable=True),
    sa.Column('be_inv_integer_max', sa.Integer(), nullable=True),
    sa.Column('be_show_paid_stamp', sa.Boolean(), nullable=True),
    sa.Column('be_plan_id', sa.Uuid(), nullable=True),
    sa.Column('be_plan_name', sa.String(length=128), nullable=True),
    sa.Column('be_plan251_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan252_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan253_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan254_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan255_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan256_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan257_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan258_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('be_plan259_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['be_plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['zme_id'], ['zme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zbe_biz_id'), 'zbe', ['biz_id'], unique=False)
    op.create_index(op.f('ix_zbe_created_by'), 'zbe', ['created_by'], unique=False)
    op.create_index(op.f('ix_zbe_id'), 'zbe', ['id'], unique=False)
    op.create_index(op.f('ix_zbe_owner_id'), 'zbe', ['owner_id'], unique=False)
    op.create_index(op.f('ix_zbe_ten_id'), 'zbe', ['ten_id'], unique=False)
    op.create_index(op.f('ix_zbe_zme_id'), 'zbe', ['zme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zbe_zme_id'), table_name='zbe')
    op.drop_index(op.f('ix_zbe_ten_id'), table_name='zbe')
    op.drop_index(op.f('ix_zbe_owner_id'), table_name='zbe')
    op.drop_index(op.f('ix_zbe_id'), table_name='zbe')
    op.drop_index(op.f('ix_zbe_created_by'), table_name='zbe')
    op.drop_index(op.f('ix_zbe_biz_id'), table_name='zbe')
    op.drop_table('zbe')
    op.drop_index(op.f('ix_plans_ten_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_owner_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_created_by'), table_name='plans')
    op.drop_index(op.f('ix_plans_biz_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
