"""fee

Revision ID: 82dd70e58574
Revises: 288e77ef469f
Create Date: 2026-03-29 17:40:59.586087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82dd70e58574'
down_revision: Union[str, Sequence[str], None] = '288e77ef469f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('fee_code', sa.String(length=64), nullable=True),
    sa.Column('fee_name', sa.String(length=128), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fee_note', sa.String(length=1024), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('zme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fees_biz_id'), 'fees', ['biz_id'], unique=False)
    op.create_index(op.f('ix_fees_created_by'), 'fees', ['created_by'], unique=False)
    op.create_index(op.f('ix_fees_fee_code'), 'fees', ['fee_code'], unique=False)
    op.create_index(op.f('ix_fees_id'), 'fees', ['id'], unique=False)
    op.create_index(op.f('ix_fees_owner_id'), 'fees', ['owner_id'], unique=False)
    op.create_index(op.f('ix_fees_ten_id'), 'fees', ['ten_id'], unique=False)
    op.create_index(op.f('ix_fees_zme_id'), 'fees', ['zme_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('pm_code', sa.String(length=64), nullable=True),
    sa.Column('pm_name', sa.String(length=128), nullable=True),
    sa.Column('pm_note', sa.String(length=1024), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('zme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_biz_id'), 'payment_methods', ['biz_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_created_by'), 'payment_methods', ['created_by'], unique=False)
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.create_index(op.f('ix_payment_methods_owner_id'), 'payment_methods', ['owner_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_pm_code'), 'payment_methods', ['pm_code'], unique=False)
    op.create_index(op.f('ix_payment_methods_ten_id'), 'payment_methods', ['ten_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_zme_id'), 'payment_methods', ['zme_id'], unique=False)
    op.create_table('taxes',
    sa.Column('tax_code', sa.String(length=64), nullable=True),
    sa.Column('tax_name', sa.String(length=128), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('tax_type', sa.String(length=64), nullable=True),
    sa.Column('tax_note', sa.String(length=1024), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('zme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxes_biz_id'), 'taxes', ['biz_id'], unique=False)
    op.create_index(op.f('ix_taxes_created_by'), 'taxes', ['created_by'], unique=False)
    op.create_index(op.f('ix_taxes_id'), 'taxes', ['id'], unique=False)
    op.create_index(op.f('ix_taxes_owner_id'), 'taxes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_taxes_tax_code'), 'taxes', ['tax_code'], unique=False)
    op.create_index(op.f('ix_taxes_ten_id'), 'taxes', ['ten_id'], unique=False)
    op.create_index(op.f('ix_taxes_zme_id'), 'taxes', ['zme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxes_zme_id'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_ten_id'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_tax_code'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_owner_id'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_id'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_created_by'), table_name='taxes')
    op.drop_index(op.f('ix_taxes_biz_id'), table_name='taxes')
    op.drop_table('taxes')
    op.drop_index(op.f('ix_payment_methods_zme_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_ten_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_pm_code'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_owner_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_created_by'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_biz_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_fees_zme_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_ten_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_owner_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_fee_code'), table_name='fees')
    op.drop_index(op.f('ix_fees_created_by'), table_name='fees')
    op.drop_index(op.f('ix_fees_biz_id'), table_name='fees')
    op.drop_table('fees')
    # ### end Alembic commands ###
