"""inv

Revision ID: 9e67b64d80b0
Revises: 25840d9bba21
Create Date: 2026-03-29 20:26:14.971716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e67b64d80b0'
down_revision: Union[str, Sequence[str], None] = '25840d9bba21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('inv_code', sa.String(length=64), nullable=True),
    sa.Column('inv_number', sa.String(length=64), nullable=True),
    sa.Column('inv_issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inv_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inv_title', sa.String(length=256), nullable=True),
    sa.Column('inv_template_id', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('client_number', sa.String(length=64), nullable=True),
    sa.Column('client_company_name', sa.String(length=256), nullable=True),
    sa.Column('client_contact_name', sa.String(length=128), nullable=True),
    sa.Column('client_contact_title', sa.String(length=128), nullable=True),
    sa.Column('client_address', sa.String(length=512), nullable=True),
    sa.Column('client_email', sa.String(length=128), nullable=True),
    sa.Column('client_secondphone', sa.String(length=64), nullable=True),
    sa.Column('client_mainphone', sa.String(length=64), nullable=True),
    sa.Column('client_fax', sa.String(length=64), nullable=True),
    sa.Column('client_website', sa.String(length=256), nullable=True),
    sa.Column('client_business_number', sa.String(length=128), nullable=True),
    sa.Column('client_currency', sa.String(length=16), nullable=True),
    sa.Column('client_tax_id', sa.String(length=128), nullable=True),
    sa.Column('client_payment_term', sa.Integer(), nullable=True),
    sa.Column('client_payment_method', sa.String(length=64), nullable=True),
    sa.Column('client_terms_conditions', sa.String(length=1024), nullable=True),
    sa.Column('client_note', sa.String(length=1024), nullable=True),
    sa.Column('inv_payment_term', sa.Integer(), nullable=True),
    sa.Column('inv_payment_requirement', sa.String(length=256), nullable=True),
    sa.Column('inv_reference', sa.String(length=256), nullable=True),
    sa.Column('inv_currency', sa.String(length=16), nullable=True),
    sa.Column('inv_subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_tax_label', sa.String(length=64), nullable=True),
    sa.Column('inv_tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('inv_tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_shipping', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_handling', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_adjustment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_other_charges_label', sa.String(length=128), nullable=True),
    sa.Column('inv_other_charges_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_paid_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_balance_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('inv_payment_status', sa.String(length=32), nullable=True),
    sa.Column('inv_tnc', sa.String(length=1024), nullable=True),
    sa.Column('inv_notes', sa.String(length=1024), nullable=True),
    sa.Column('inv_flag_word', sa.String(length=64), nullable=True),
    sa.Column('inv_flag_emoji', sa.String(length=16), nullable=True),
    sa.Column('inv_pdf_template', sa.String(length=64), nullable=True),
    sa.Column('inv_terms_conditions', sa.String(length=1024), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('zme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_biz_id'), 'invoices', ['biz_id'], unique=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_created_by'), 'invoices', ['created_by'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_inv_code'), 'invoices', ['inv_code'], unique=False)
    op.create_index(op.f('ix_invoices_owner_id'), 'invoices', ['owner_id'], unique=False)
    op.create_index(op.f('ix_invoices_ten_id'), 'invoices', ['ten_id'], unique=False)
    op.create_index(op.f('ix_invoices_zme_id'), 'invoices', ['zme_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('inv_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('item_code', sa.String(length=64), nullable=True),
    sa.Column('item_number', sa.String(length=64), nullable=True),
    sa.Column('item_name', sa.String(length=256), nullable=True),
    sa.Column('item_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('item_unit_of_measure', sa.String(length=64), nullable=True),
    sa.Column('item_unit', sa.String(length=64), nullable=True),
    sa.Column('item_sku', sa.String(length=128), nullable=True),
    sa.Column('item_description', sa.String(length=1024), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('item_note', sa.String(length=1024), nullable=True),
    sa.Column('item_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('zme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inv_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_biz_id'), 'invoice_items', ['biz_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_created_by'), 'invoice_items', ['created_by'], unique=False)
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_items_inv_id'), 'invoice_items', ['inv_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_item_code'), 'invoice_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_invoice_items_owner_id'), 'invoice_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_ten_id'), 'invoice_items', ['ten_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_zme_id'), 'invoice_items', ['zme_id'], unique=False)
    op.create_table('invoice_payments',
    sa.Column('inv_id', sa.Uuid(), nullable=False),
    sa.Column('pm_id', sa.Uuid(), nullable=True),
    sa.Column('pm_code', sa.String(length=64), nullable=True),
    sa.Column('pm_name', sa.String(length=128), nullable=True),
    sa.Column('pm_note', sa.String(length=1024), nullable=True),
    sa.Column('pay_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pay_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pay_reference', sa.String(length=256), nullable=True),
    sa.Column('pay_note', sa.String(length=1024), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('zme_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inv_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['pm_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_payments_biz_id'), 'invoice_payments', ['biz_id'], unique=False)
    op.create_index(op.f('ix_invoice_payments_created_by'), 'invoice_payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_invoice_payments_id'), 'invoice_payments', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_payments_inv_id'), 'invoice_payments', ['inv_id'], unique=False)
    op.create_index(op.f('ix_invoice_payments_owner_id'), 'invoice_payments', ['owner_id'], unique=False)
    op.create_index(op.f('ix_invoice_payments_pm_code'), 'invoice_payments', ['pm_code'], unique=False)
    op.create_index(op.f('ix_invoice_payments_ten_id'), 'invoice_payments', ['ten_id'], unique=False)
    op.create_index(op.f('ix_invoice_payments_zme_id'), 'invoice_payments', ['zme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_payments_zme_id'), table_name='invoice_payments')
    op.drop_index(op.f('ix_invoice_payments_ten_id'), table_name='invoice_payments')
    op.drop_index(op.f('ix_invoice_payments_pm_code'), table_name='invoice_payments')
    op.drop_index(op.f('ix_invoice_payments_owner_id'), table_name='invoice_payments')
    op.drop_index(op.f('ix_invoice_payments_inv_id'), table_name='invoice_payments')
    op.drop_index(op.f('ix_invoice_payments_id'), table_name='invoice_payments')
    op.drop_index(op.f('ix_invoice_payments_created_by'), table_name='invoice_payments')
    op.drop_index(op.f('ix_invoice_payments_biz_id'), table_name='invoice_payments')
    op.drop_table('invoice_payments')
    op.drop_index(op.f('ix_invoice_items_zme_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_ten_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_owner_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_item_code'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_inv_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_created_by'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_biz_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_zme_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_ten_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_owner_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_inv_code'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_by'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_biz_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
