"""zme

Revision ID: a717e138b33d
Revises: 3d721c93922f
Create Date: 2026-03-29 12:18:07.977415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a717e138b33d'
down_revision: Union[str, Sequence[str], None] = '3d721c93922f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zme',
    sa.Column('plan_type', sa.String(length=64), nullable=True),
    sa.Column('plan_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('reddit', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pin', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('tax_no', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zme_biz_id'), 'zme', ['biz_id'], unique=False)
    op.create_index(op.f('ix_zme_created_by'), 'zme', ['created_by'], unique=False)
    op.create_index(op.f('ix_zme_email'), 'zme', ['email'], unique=True)
    op.create_index(op.f('ix_zme_id'), 'zme', ['id'], unique=False)
    op.create_index(op.f('ix_zme_owner_id'), 'zme', ['owner_id'], unique=False)
    op.create_index(op.f('ix_zme_ten_id'), 'zme', ['ten_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zme_ten_id'), table_name='zme')
    op.drop_index(op.f('ix_zme_owner_id'), table_name='zme')
    op.drop_index(op.f('ix_zme_id'), table_name='zme')
    op.drop_index(op.f('ix_zme_email'), table_name='zme')
    op.drop_index(op.f('ix_zme_created_by'), table_name='zme')
    op.drop_index(op.f('ix_zme_biz_id'), table_name='zme')
    op.drop_table('zme')
    # ### end Alembic commands ###
